# Generated by Django 4.0.2 on 2023-10-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='horario',
        ),
        migrations.AddField(
            model_name='evento',
            name='horario_fin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='horario_inicio',
            field=models.CharField(default='00:00:00', max_length=100),
            preserve_default=False,
        ),
    ]
