# Generated by Django 4.0.2 on 2023-11-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_categoria_documento_document_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria_documento',
            new_name='Categoria_doc',
        ),
    ]
