# Generated by Django 4.0.2 on 2023-11-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_noticia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default='app/img/logo.png', upload_to='noticias/'),
        ),
    ]
