# Generated by Django 4.0.2 on 2023-12-07 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='archivo',
            field=models.FileField(upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.MaxLengthValidator(limit_value=10485760)]),
        ),
    ]
