# Generated by Django 4.0.2 on 2023-12-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_document_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='archivo',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
