# Generated by Django 4.0.2 on 2023-12-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_document_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
