# Generated by Django 4.0.2 on 2023-12-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
